import Head from "next/head"
import Image from "next/image"
import { checkout } from "../../checkout"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Our Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' min-h-[100vh] flex justify-center flex-col items-center' >
            <p>Donate here</p>
            <form className='flex flex-col'>
            <label>Your Name</label>
            <input type='text' value='name' className='bg-gray-300 text-gray-700 mt-2 w-64 p-3 rounded-sm' />
            
            <label className='mt-2'>Amount</label>
            <input type='text' value='name' className='bg-gray-300 text-gray-700 mt-2 w-64 p-3 rounded-sm' />
            </form>
            <button className='mt-4 p-2 bg-gray-700 hover:bg-gray-800 rounded-sm' onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1N2gLlAy6kbtVnGKmvjkxdgC",
                    quantity: 1
                  }
                ]
              })
            })}>Donate</button>
      </main>
    </div>
  )
}