import Head from "next/head"
import Image from "next/image"
import { checkout } from "../../checkout"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Our Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
            <p>Donate here</p>
            <button onClick={(() => {
              checkout({
                lineItems: [
                  {
                    price: "price_1N2gLlAy6kbtVnGKmvjkxdgC",
                    quantity: 1
                  }
                ]
              })
            })}>Donate here!</button>
      </main>
    </div>
  )
}