import Head from "next/head"

import Link from 'next/link'

export default function Home() {
  
  return (
    <div>
      <Head>
        <title>Simple Shopping</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' min-h-[100vh] flex justify-center flex-col items-center' >
            <h1 className='font-heading text-2xl'>Welcome to 
            <span className='text-orange-500 font-body' > Simple Shopping</span></h1>

            <h4 className='text-lg font-heading'>Shop Here</h4>
            
              <Link href='/shop' >
                <button className='mt-4 p-2 bg-orange-500 hover:bg-emerald-700 rounded-sm'>Shop</button>
              </Link>

            <h4 className='text-lg font-heading'>We also Accept donations</h4>
              <Link href="https://donate.stripe.com/test_5kA9DLcZD8b8eLm7ss">
                <button className='mt-4 p-2 bg-emerald-700 hover:bg-blue-800 rounded-sm'>Donate</button>
              </Link>
            
            
      </main>
    </div>
  )
}